version: '3.5'
services:

  app:
    build: .
    image: &app app
    restart: "no"
#    command: ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
    env_file: &envfile
      - env.env
#    ports:
#      - "8000:8000"
    volumes:
      - ./app:/app
#    depends_on:
#      - broker

  worker:
    build: .
    image: *app
    restart: "no"
    env_file: *envfile
    command: ["celery", "worker", "--app=worker.worker_conf.app", "-Q", "app.worker.tasks.get_equally_separated_points", "--concurrency=1", "--loglevel=INFO"]
    networks:
      - rabbit
    volumes:
      - ./app:/app
#
#networks:
#  rabbit:
#    external: true
#
  rabbitmq:
      image: rabbitmq:3.7.13-management
      networks:
        - "rabbit"
      ports:
        - "5672:5672"
        - "15672:15672"
      volumes:
        - "rabbitmq_data:/data"
      env_file:
        - env.env
      environment:
        - "TZ=Asia/Almaty"
networks:
  rabbit:
    external:
      name: "rabbit"

volumes:
  rabbitmq_data:
    external: true
